# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

kubemasters = [
  "kubemaster1",
  "kubemaster2",
  "kubemaster3",
]
kubenodes = [
  "kubeworker1",
  "kubeworker2",
]

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |domain|
    domain.memory = 2048
    domain.cpus = 2
    domain.nested = true
    domain.volume_cache = 'writeback'
    # cloud-init via ISO CD-ROM
    domain.storage :file, :device => :cdrom, :bus => :ide, :type => :raw, :path => "/home/falfaro/k8s/cloud-init/testing-cidata.iso"
  end

  # Use :ansible or :ansible_local to
  # select the provisioner of your choice
  config.vm.provision :ansible do |ansible|
    ansible.compatibility_mode = '2.0'
    ansible.playbook = "../kubespray/cluster.yml"
    ansible.become = true
    ansible.limit = "all"
    ansible.host_key_checking = false
    #ansible.raw_arguments = ["--forks=#{$num_instances}"]
    #ansible.host_vars = {
    #  "default" => {
    #    "ansible_python_interpreter" => "/usr/bin/pytho3"
    #    }
    #  }
    #ansible.tags = ['download']
    ansible.groups = {
      "etcd" => kubemasters,
      "kube-master" => kubemasters,
      "kube-node" => kubenodes,
      "k8s-cluster:children" => [
        "kube-master",
	"kube-node",
      ],
      "k8s-clusters:vars" => {
        "kube_network_plugin" => "flannel"
      }
    }
  end

  # SSH configuration
  config.ssh.username = "ubuntu"
  config.ssh.insert_key = FALSE
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # Defaults to Ubuntu 16.04 (Xenial)
  config.vm.box = "xenial"

  (kubemasters + kubenodes).each do |i|
    config.vm.define i do |node|
      node.vm.hostname = i
    end
  end
end
