all: CentOS-7-x86_64-Vagrant-1708_01.Libvirt.box

CentOS-7-x86_64-Vagrant-1708_01.Libvirt.box:
	wget http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1708_01.Libvirt.box
	vagrant box add CentOS-7-x86_64-Vagrant-1708_01.Libvirt.box --name centos7
