- hosts: all
  become: true
  vars:
    packages:
    - docker
    - git
    - centos-release-openshift-origin
    - origin-clients
    - wget
    # Required to remove some annoying Docker warnings about netfilter
    sysctls:
    - name: net.bridge.bridge-nf-call-iptables
      value: 1
    - name: net.bridge.bridge-nf-call-ip6tables
      value: 1
  handlers:
  - name: Restart Docker
    service:
      name: docker
      state: restarted
  tasks:
  - name: Ensure kernel modules are loaded
    modprobe:
      name: br_netfilter 
  - name: Configure sysctl values
    sysctl:
      name: "{{item.name}}"
      value: "{{item.value}}"
      state: present
    with_items: "{{sysctls}}"
  - name: Ensure packages are installed
    package:
      name: "{{item}}"
      state: latest
    with_items: "{{packages}}"
  - seboolean:
      name: virt_use_nfs
      state: yes
  - name: Ensure proper Docker configuration
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
    notify: Restart Docker
  - name: Ensure proper Docker storage configuration
    copy:
      src: docker-storage-setup 
      dest: /etc/sysconfig/docker-storage-setup 
    notify: Restart Docker
  - name: Enable Docker
    service:
      name: docker
      enabled: yes
  - meta: flush_handlers
  - name: Deploy OpenShift
    command: oc cluster up
    args:
      creates: /root/.kube
  - name: Pull OpenShift from git
    git:
      repo: "https://github.com/falfaro/origin.git"
      dest: /root/origin
  - name: Pull Kubernetes from git
    git:
      repo: 'https://github.com/falfaro/kubernetes.git'
      dest: /root/kubernetes
  - name: Switch to an OpenShift admin context
    command: oc login -u system:admin
